### ISSUE TITLE
TODO redesign branch content review

### ISSUE THREAD

**Issue by anajsana** [todogroup/todogroup.org#385]
By looking at https://redesign--todogroup.netlify.app/ here are a few actions that I would recommend to be done to improve User experience and make easier for the community to navigate across pages:

## INDEX PAGE:
- [x] Slogan change it to “for organizations and practitioners” or just “for open source practitioners committed to Open Source Program Offices (OSPOs)” or “for open source practitioners and organizations committed to Open Source Program Offices (OSPOs)”
- [x] Include in the description: TODO Group is formed by its community participants *and ambassadors, OSPO Associates* and general members.
- [x] Change twitter logo for “X” logo
- [x]  Include TODO mastodon social icon and link
- [x] Footer: change join TODO for “join”
- [x] Get involved social cards: fix the typo “OSPA” to “OSPO”

## ABOUT

- [x] Include navbar subsection Called *Member Charter* which contents mirrors: https://github.com/todogroup/governance/blob/main/GM-SC-CHARTER.adoc

### Get Started

- [ ] Include cards with

* Onboarding Checklist: https://github.com/todogroup/governance/blob/main/onboarding/community.md
* TODO Structure: https://github.com/todogroup/governance/blob/main/TODO%20Structure/structure-mindmap.md#todo-groups-structure
* Contributor Ladder: https://github.com/todogroup/ospology/blob/main/GOVERNANCE.md
* Working Repo: https://github.com/todogroup

### Virtual Meetings

- [ ] Use card mode with the following sections:

* OSPOlogy

   * Global OSPOlogy Panel Discussions: Expert-Led and community panel discussions to address OSPO common challenges and topics of interest. Find in the Calendar (link to calendar section) the next call or [watch the recordings](https://www.youtube.com/@ospology)
   * Regional OSPOlogy: Meetups led by local OSPOers, usually in their native language. include Buttons “Asia” “Europe”. Find in the Calendar (link to calendar section) the next call
   
* Local Groups:

   * Japanese OSPO Local Meetup supported by openChain and TODO. Include Button Join
   
* Working Groups

   * Employee open source engagement WG. Include Button Join
   * OSPO Career Path & Training WG.  Include Button Join
   * CHAOSS OSPO Metrics WG. Include Button Join

- [x] Leave Calendar view as it is

### Events:

- [ ] Use card mode with the following sections:

* [OSPOCon Events](https://events.linuxfoundation.org/?_sf_s=OSPOCon)
* [OSPOlogyLive Micro-conferences](https://community.linuxfoundation.org/ospology-european-chapter/)
* [OSPO BoF + Happy Hour]()

### Mindmap:

- [x] Q: Can the O[SPO mind map be embedded in the TODO website](https://ospomindmap.todogroup.org/)? If not, including a screenshot of the mind cap can work

- [x] TODO Structure paragraph (remove from mindmap)

### Studies:

- [x] Q: Can we have images of the studies? A card mode similar to this one (image attached) would work. for same reports in different languages, use different cards (e.g one card for "the value of the ospo" report english version, other one for "the value of the ospo japanese version, etc)
![Screenshot 2023-08-21 at 10-22-59 Research Linux Foundation](https://github.com/todogroup/todogroup.org/assets/43671777/89ac0728-f36a-4c11-b370-965234fba66e)

### Case studies

- [x] Change the first two paragraphs to Organizations across sectors who contribute to TODO by sharing case studies on OSPO best practices
- [x] Can we have images of the ospo use cases? just a standard cover image (e. green gradient from now on can work)

### Glossary

- [x] Include description: “The world of open source is vast and complex, with many different terms and concepts that can be difficult to navigate. Our aim with this glossary is not to provide a definitive or general definition of these terms, but to clarify what we mean specifically under the context of an OSPO framework (stratey, governance, compliance and community) for organizations.”
- [x] Add buttons: Explore (https://ospoglossary.todogroup.org/) AND Contribute (https://ospoglossary.todogroup.org/contribute/)

Guides:

Remove OSPO 101 course and annual surveys
* Title only shows OSPO guides
* Separate by themes: Strategy / Community / Structure
* Remove TODO Guides Contributing Guidelines, Open Source Program Office Case Study Guidelines and TODO Whitepaper Guidelines

Training Modules:

- [x] Add OSPO 101 course content that where in the guide section in the training modules section. Include titles of the course (each title within a card mode):
    *[ Open Source Introduction](https://github.com/todogroup/ospo-career-path/tree/main/OSPO-101/module1)
        * Introducing Open Source
        * A Short History of Open Source Software
        * Reasons to Use Open Source
    * [Open Source Business Strategy](https://github.com/todogroup/ospo-career-path/tree/main/OSPO-101/module2)
        * Introducing Open Source Business Models
        * Developing an Open Source Strategy
        * Developing Open Source Policies
        * Introducing the Open Source Program Office (OSPO)
    * [Effective Open Source Program (OSPO) Management](https://github.com/todogroup/ospo-career-path/tree/main/OSPO-101/module3)
        * Open Source Program Offices & Your Organization
        * Building an Effective Open Source Program Office
        * Additional Information & Case Studies
    * [Open Source Development Practices](https://github.com/todogroup/ospo-career-path/tree/main/OSPO-101/module4)
        * Effective Open Source Development & Participation
        * The Role of Continuous Integration & Testing
        * Applying Open Source Methodologies Internally
    * [Open Source Compliance Programs](https://github.com/todogroup/ospo-career-path/tree/main/OSPO-101/module5)
        * Open Source Licensing and Compliance Basics
        * Building an Effective Compliance Program
        * Choosing the Right License Compliance Tool
        * The Role of Open Source Audits During M&A Activities
    * [Collaborating Effectively with Open Source Projects](https://github.com/todogroup/ospo-career-path/tree/main/OSPO-101/module6)
        * Understanding Upstream Open Source Projects
        * Effective Upstream Contribution Strategies
        * Upstream Development Practices
    * Creating Open Source Projects
        * Open Source Project Creation Overview
        * New Project Preparations
        * Successful Project Launch & Sustainment

**Comment by anajsana** [comment]
Update: I've marked some of the tasks documented in this issue as completed since I've implemented them in the `redesign` branch 👍

**Comment by jansche** [comment]
Coming back from a discussion with @anajsana I wanted to drop a note on accessibility of the new design. I love the new contrast colors and also am a fan of brand guidelines. One thing to mention though is that accessibility for both the iframe that holds the google slides as well as the slides themselves should be checked. Problems with accessibility are common in that field. Happy to help there as well.

**Comment by thetwopct** [comment]
Good point, thanks. The iFrames need a title to be accessible. We'll do a final sweep of accessibility and performance improvements before launch and I've made a note to add a title to the static iFrame content and also add the title as a requirement of the iFrame custom shortcode.

**Comment by cjyabraham** [comment]
I've moved the remaining items on this issue to [a new clean issue](https://github.com/todogroup/todogroup.org/issues/387)
